# Generated by Django 5.2.4 on 2025-08-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_postimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='image',
        ),
        migrations.AddField(
            model_name='postimage',
            name='file',
            field=models.FileField(default=None, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='title',
            field=models.CharField(default='Untitled', max_length=200),
        ),
    ]
