# Generated by Django 5.2.4 on 2025-08-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_postimage_image_postimage_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
